Repository k-next/kirby, pull requests merged in 2018-03, with the labels that each got.

#48 More precise section min/max error messages
  src/Cms/Mixins/BlueprintSectionMax.php
  src/Cms/Mixins/BlueprintSectionMin.php
Labels: status: in review 👀, type: enhancement ✨

#51 Move APC cache to APCu
  src/Cache/ApcuCache.php
  src/Cms/AppCaches.php
Labels: priority: low-hanging fruit 🍓, status: in review 👀

#54 Simplify Snippet extending Template
  src/Cms/Snippet.php
  src/Cms/Template.php
Labels: status: in review 👀, type: enhancement ✨, type: idea 💡

#56 Use pattern as image background in sections
  src/Cms/Mixins/BlueprintSectionData.php
Labels: status: in review 👀, type: bug 🐛

#52 Cookie class refactoring
  src/Http/Cookie.php
  tests/Http/CookieTest.php
Labels: status: in review 👀

#60 Add Kirby\Exception package
  locales/de_DE.json
  locales/en_US.json
  src/Cms/App.php
  src/Cms/Blueprint.php
  src/Cms/BlueprintObject.php
  src/Cms/BlueprintTabs.php
  src/Cms/Mixins/BlueprintSectionHeadline.php
  src/Exception/BadMethodCallException.php
  src/Exception/DuplicateException.php
  src/Exception/Exception.php
  src/Exception/InvalidArgumentException.php
  src/Exception/LogicException.php
  src/Exception/NotFoundException.php
  src/Exception/PermissionException.php
  src/Form/Field.php
  src/Form/Form.php
  src/Form/Mixins/Help.php
  src/Form/Mixins/Label.php
  src/Form/Mixins/Options.php
  src/Form/Mixins/Placeholder.php
  src/Form/Mixins/Text.php
  src/Util/Str.php
  src/Util/Translate.php
  tests/Cms/AppLocalesTest.php
  tests/Exception/BadMethodCallExceptionTest.php
  tests/Exception/DuplicateExceptionTest.php
  tests/Exception/ExceptionTest.php
  tests/Exception/InvalidArgumentExceptionTest.php
  tests/Exception/LogicExceptionTest.php
  tests/Exception/NotFoundExceptionTest.php
  tests/Exception/PermissionExceptionTest.php
  tests/Form/Assertions/Help.php
  tests/Form/Assertions/Label.php
  tests/Form/Assertions/Placeholder.php
  tests/Form/FieldTestCase.php
  tests/Util/StrTest.php
Labels: status: in review 👀, type: enhancement ✨
