Repository k-next/kirby, pull requests merged in 2018-04, with the labels that each got.

#65 Implement page methods from plugins
  src/Cms/AppPlugins.php
  src/Cms/ContentField.php
  src/Cms/Extend.php
  src/Cms/HasMethods.php
  src/Cms/Page.php
  tests/Cms/AppPluginsTest.php
  tests/Cms/ContentFieldTest.php
  tests/Cms/HasMethodTest.php
Labels: status: in review 👀, type: feature ⭐️

#63 changeNum on update if based on content value
  src/Cms/Page.php
Labels: status: in review 👀, type: enhancement ✨

#67 Implement Site::changeTitle
  config/api/routes/site.php
  src/Cms/SiteActions.php
  src/Cms/SiteRules.php
  src/Cms/SiteStoreDefault.php
Labels: status: in review 👀, type: feature ⭐️

#70 Implement turning off translation for Exceptions
  src/Exception/Exception.php
  tests/Cms/AppLocalesTest.php
Labels: status: in review 👀, type: enhancement ✨

#73 Session: Proxy method calls to SessionData class
  src/Session/Session.php
  tests/Session/SessionTest.php
Labels: status: in review 👀, type: enhancement ✨

#74 Session: Rename length property to duration
  src/Session/AutoSession.php
  src/Session/Session.php
  tests/Session/AutoSessionTest.php
  tests/Session/SessionTest.php
  tests/Session/mocks.php
Labels: status: in review 👀, type: refactoring :recycle:

#75 Rename Locales to Translations
  config/api/collections.php
  config/api/models.php
  config/api/models/Locale.php
  config/api/models/Translation.php
  config/api/routes.php
  config/api/routes/translations.php
  config/components.php
  config/helpers.php
  src/Cms/App.php
  src/Cms/AppTranslations.php
  src/Cms/Roots.php
  src/Cms/Translation.php
  src/Cms/Translations.php
  src/Cms/UserRules.php
  translations/de_DE.json
  translations/en_US.json
Labels: status: in review 👀, type: enhancement ✨

#77 Translations for refactored plugin views
  translations/de_DE.json
  translations/en_US.json
Labels: status: blocked 🚧, type: translation 🌎

#81 Fix NumberField::valueFromInput
  src/Form/NumberField.php
Labels: status: in review 👀, type: bug 🐛
